/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0A)
#define ID_TEXT_10 (GUI_ID_USER + 0x0B)
#define ID_TEXT_11 (GUI_ID_USER + 0x0C)
#define ID_TEXT_12 (GUI_ID_USER + 0x0D)
#define ID_TEXT_13 (GUI_ID_USER + 0x0E)
#define ID_TEXT_14 (GUI_ID_USER + 0x0F)
#define ID_TEXT_15 (GUI_ID_USER + 0x10)
#define ID_TEXT_16 (GUI_ID_USER + 0x11)
#define ID_TEXT_17 (GUI_ID_USER + 0x12)
#define ID_TEXT_18 (GUI_ID_USER + 0x13)
#define ID_BUTTON_0 (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Hex", ID_WINDOW_0, 6, 8, 319, 199, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Chip", ID_TEXT_0, 4, 4, 74, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ChipVal", ID_TEXT_1, 91, 23, 215, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Checksum:", ID_TEXT_2, 20, 42, 68, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ChecksumVal", ID_TEXT_3, 90, 41, 71, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Options:", ID_TEXT_4, 165, 42, 48, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OptionsVal", ID_TEXT_5, 217, 40, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Rolling Code", ID_TEXT_6, 4, 58, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Init:", ID_TEXT_7, 18, 92, 36, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Type:", ID_TEXT_8, 18, 21, 54, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Step:", ID_TEXT_9, 166, 76, 42, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "StepVal", ID_TEXT_10, 217, 76, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Width(Bits):", ID_TEXT_11, 17, 76, 74, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WidthVal", ID_TEXT_12, 91, 76, 68, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Program Limit", ID_TEXT_13, 4, 110, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Max Num:", ID_TEXT_14, 18, 129, 55, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "MaxVal", ID_TEXT_15, 136, 129, 63, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "InitVal", ID_TEXT_16, 91, 92, 187, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Restrict CSWrite:", ID_TEXT_17, 18, 147, 105, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "RestrictVal", ID_TEXT_18, 136, 147, 53, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 236, 204, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void keyProcess(WM_MESSAGE* pMsg)
{
    int index;
    WM_HWIN hParent;
    WM_KEY_INFO* keyInfo;

    keyInfo = (WM_KEY_INFO*)pMsg->Data.p;

    printf("[GUI] Hex     , %s(),Msg(Key=%d,PressedCnt=%d)\n", __func__, keyInfo->Key, keyInfo->PressedCnt);

    WM_DefaultProc(pMsg);
}
static void initHex(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    
    struct tlv_chip*   chip;
    struct tlv_code*   code;
    struct tlv_option* option;
    struct tlv_limit*  limit;
    struct tlv_rolling_code* rolling;
    char               buf[128];
    
    //
    // Initialization of 'ChipVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    chip = file_hex_get_chip(0);
    if (chip) {
        TEXT_SetText(hItem, (const char*)chip->name);
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ChecksumVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    code = file_hex_get_code(0);
    if (code) {
        memset(buf, 0, sizeof(buf));
        snprintf(buf, sizeof(buf), "0x%04X", code->checksum);
        TEXT_SetText(hItem, buf); 
    }    
    TEXT_SetFont(hItem, GUI_FONT_13B_1); 
    //
    // Initialization of 'OptionsVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    option = file_hex_get_option(1);
    if (option) {
        int i;
        char tmp[4];
        
        memset(buf, 0, sizeof(buf));
        strcpy(buf, "0x");
        for (i = 0; i < option->option_len; i++) {
            snprintf(tmp, sizeof(tmp), "%02X", option->bytes[i]);
            strcat(buf, tmp);
        }
        TEXT_SetText(hItem, buf); 
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1);   
    //
    // Initialization of 'StepVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "1");
    //
    // Initialization of 'WidthVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "96");
    //
    // Initialization of 'MaxVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "99999999");
    //
    // Initialization of 'InitVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "0x12345678");
    //
    // Initialization of 'RestrictVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "No");
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Chip'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'Checksum:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Options:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Rolling Code'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'Init:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Type:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Step:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Width(Bits):'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Program Limit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'Max Num:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Restrict CSWrite:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    // USER START (Optionally insert additional code for further widget initialization)
    initHex(pMsg);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateHex
*/
WM_HWIN CreateHex(void);
WM_HWIN CreateHex(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
