/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0A)
#define ID_TEXT_10 (GUI_ID_USER + 0x0B)
#define ID_TEXT_11 (GUI_ID_USER + 0x0C)
#define ID_TEXT_12 (GUI_ID_USER + 0x0D)
#define ID_TEXT_13 (GUI_ID_USER + 0x0E)
#define ID_TEXT_14 (GUI_ID_USER + 0x0F)
#define ID_TEXT_15 (GUI_ID_USER + 0x10)
#define ID_BUTTON_0 (GUI_ID_USER + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Chip", ID_WINDOW_0, 0, 0, 320, 199, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Chip", ID_TEXT_0, 7, 4, 78, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Type:", ID_TEXT_1, 15, 24, 52, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "tVal", ID_TEXT_2, 57, 25, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Program Status", ID_TEXT_3, 5, 44, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "sVal", ID_TEXT_4, 15, 63, 249, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Trim Inforamtion", ID_TEXT_5, 7, 81, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OSCTrim:", ID_TEXT_6, 20, 99, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0xAB", ID_TEXT_7, 94, 99, 39, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Error:", ID_TEXT_8, 136, 99, 38, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "eVal", ID_TEXT_9, 172, 99, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WDTTrim:", ID_TEXT_10, 20, 115, 53, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "wVal", ID_TEXT_11, 93, 116, 35, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Error:", ID_TEXT_12, 136, 115, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "errorVal", ID_TEXT_13, 170, 115, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "ADCTrim:", ID_TEXT_14, 21, 132, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0xCD", ID_TEXT_15, 93, 133, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Chip Read", ID_BUTTON_0, 203, 160, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void keyProcess(WM_MESSAGE* pMsg)
{
    int index;
    WM_HWIN hParent;
    WM_KEY_INFO* key;

    key = (WM_KEY_INFO*)pMsg->Data.p;
 
    printf("[GUI] Chip    , %s(),Msg(Key=%d,PressedCnt=%d)\n", __func__, key->Key, key->PressedCnt);

    hParent = WM_GetParent(pMsg->hWin);
    hParent = WM_GetParent(hParent);
    index = MULTIPAGE_GetSelection(hParent);
    
    if (index == 4 && key->Key == GUI_KEY_PGDOWN) {
        MULTIPAGE_SelectPage(hParent, 0);
    } else {
        WM_DefaultProc(pMsg);
    }
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Chip'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Type:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'tVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "CSU8RP3429");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Program Status'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'sVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "Programmed/Blank/Erased/Read Protected");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Trim Inforamtion'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'OSCTrim:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of '0xAB'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Error:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'eVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'WDTTrim:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'wVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetText(hItem, "0xBA");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Error:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'errorVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetText(hItem, "0x12");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ADCTrim:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of '0xCD'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Chip Read'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    keyProcess(pMsg);
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateChip
*/
WM_HWIN CreateChip(void);
WM_HWIN CreateChip(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
