/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "gui_main.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0      (ID_PAGE_CHIP + 0x00)
#define ID_TEXT_0        (ID_PAGE_CHIP + 0x01)
#define ID_TEXT_1        (ID_PAGE_CHIP + 0x02)
#define ID_TEXT_2        (ID_PAGE_CHIP + 0x03)
#define ID_TEXT_3        (ID_PAGE_CHIP + 0x04)
#define ID_TEXT_4        (ID_PAGE_CHIP + 0x05)
#define ID_TEXT_5        (ID_PAGE_CHIP + 0x06)
#define ID_TEXT_6        (ID_PAGE_CHIP + 0x07)
#define ID_TEXT_7        (ID_PAGE_CHIP + 0x08)
#define ID_TEXT_8        (ID_PAGE_CHIP + 0x0B)
#define ID_TEXT_9        (ID_PAGE_CHIP + 0x0C)
#define ID_TEXT_10       (ID_PAGE_CHIP + 0x0F)
#define ID_TEXT_11       (ID_PAGE_CHIP + 0x10)
#define ID_BUTTON_0      (ID_PAGE_CHIP + 0x11)
#define ID_TEXT_12       (ID_PAGE_CHIP + 0x12)
#define ID_TEXT_13       (ID_PAGE_CHIP + 0x13)
#define ID_TEXT_14       (ID_PAGE_CHIP + 0x14)
#define ID_TEXT_15       (ID_PAGE_CHIP + 0x15)
#define ID_TEXT_16       (ID_PAGE_CHIP + 0x16)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Chip", ID_WINDOW_0, 0, 0, 320, 199, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Chip", ID_TEXT_0, 4, 4, 78, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Type:", ID_TEXT_1, 16, 21, 52, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TypeVal", ID_TEXT_2, 89, 24, 178, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Program Status", ID_TEXT_3, 4, 38, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "StatusVal", ID_TEXT_4, 88, 56, 87, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Trim Inforamtion", ID_TEXT_5, 4, 93, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OSCTrim:", ID_TEXT_6, 22, 114, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OSCVal", ID_TEXT_7, 89, 114, 60, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "WDTTrim:", ID_TEXT_8, 173, 114, 62, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WDTVal", ID_TEXT_9, 238, 114, 64, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "ADCTrim:", ID_TEXT_10, 22, 134, 61, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ADCVal", ID_TEXT_11, 89, 134, 40, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Chip Read", ID_BUTTON_0, 216, 151, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Status:", ID_TEXT_12, 15, 56, 49, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CheckSum:", ID_TEXT_13, 15, 72, 67, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CheckSumVal", ID_TEXT_14, 88, 74, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Options:", ID_TEXT_15, 182, 56, 53, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OptionVal", ID_TEXT_16, 242, 57, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void keyProcess(WM_MESSAGE* pMsg)
{
    int index;
    WM_HWIN hParent;
    WM_KEY_INFO* key;

    key = (WM_KEY_INFO*)pMsg->Data.p;

    printf("[GUI] Chip    , %s(),Msg(Key=%d,PressedCnt=%d)\n", __func__, key->Key, key->PressedCnt);


    WM_DefaultProc(pMsg);
    
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Chip'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'Type:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'TypeVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "CSU8RP3429");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Program Status'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'StatusVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "Programmed");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Trim Inforamtion'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'OSCTrim:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'OSCVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetText(hItem, "0xABCD");
    //
    // Initialization of 'WDTTrim:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'WDTVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetText(hItem, "0xDCBA");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ADCTrim:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'ADCVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "0x1234");
    //
    // Initialization of 'Status:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'CheckSum:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'CheckSumVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "0x12345678");
    //
    // Initialization of 'Options:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'OptionVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetText(hItem, "0x12345678");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Chip Read'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    keyProcess(pMsg);
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateChip
*/
WM_HWIN CreateChip(void);
WM_HWIN CreateChip(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
