/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "gui_main.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0            (GUI_ID_USER + 0x00)
#define ID_MULTIPAGE_0           (GUI_ID_USER + 0x01)
#define ID_TEXT_0                (GUI_ID_USER + 0x02)
#define ID_TEXT_1                (GUI_ID_USER + 0x03)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x64, 0 },
  { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_0, 0, 0, 311, 200, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Status:", ID_TEXT_0, 0, 202, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "status_val", ID_TEXT_1, 53, 202, 253, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void keyProcess(WM_MESSAGE* pMsg)
{
    int index;
    WM_HWIN hParent;
    WM_KEY_INFO* key;

    key = (WM_KEY_INFO*)pMsg->Data.p;

    printf("[GUI] Framewin, %s(),Msg(Key=%d,PressedCnt=%d)\n", __func__, key->Key, key->PressedCnt);

     WM_DefaultProc(pMsg);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN hStatus;
  WM_HWIN hStatusVal;
  WM_HWIN hSummary;
  WM_HWIN hHexInfo;
  WM_HWIN hCSWrite;
  WM_HWIN hConfig;
  WM_HWIN hChip;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "CSWrite3.0.1");
    //
    // Initialization of 'Multipage'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
    MULTIPAGE_AddEmptyPage(hItem, 0, "Summary");
    MULTIPAGE_AddEmptyPage(hItem, 0, "HEX Info");
    MULTIPAGE_AddEmptyPage(hItem, 0, "CSWrite Info");
    MULTIPAGE_AddEmptyPage(hItem, 0, "Chip Info");
    MULTIPAGE_AddEmptyPage(hItem, 0, "Configuration");
    //
    // Initialization of 'Status:'
    //
    hStatus = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hStatus, GUI_FONT_13B_1);
    //
    // Initialization of 'status_val'
    //
    hStatusVal = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hStatusVal, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)

    hSummary = CreateSummary();
    MULTIPAGE_AttachWindow(hItem, 0, hSummary);
    hHexInfo = CreateHex();
    MULTIPAGE_AttachWindow(hItem, 1, hHexInfo);
    hCSWrite = CreateCSWrite();
    MULTIPAGE_AttachWindow(hItem, 2, hCSWrite);
    hChip = CreateChip();
    MULTIPAGE_AttachWindow(hItem, 3, hChip);
    hConfig = CreateConfig();
    MULTIPAGE_AttachWindow(hItem, 4, hConfig);
    MULTIPAGE_SelectPage(hItem, 0);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    keyProcess(pMsg);
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
