/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include "gui_main.h"
#include "tlv.h"
#include "file_hex.h"
#include "cswrite_cfg.h"
#include "power.h"
#include "cswrite_log.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0          (ID_PAGE_SUMMARY + 0x00)
#define ID_TEXT_0            (ID_PAGE_SUMMARY + 0x01)
#define ID_TEXT_1            (ID_PAGE_SUMMARY + 0x02)
#define ID_TEXT_2            (ID_PAGE_SUMMARY + 0x03)
#define ID_TEXT_3            (ID_PAGE_SUMMARY + 0x04)
#define ID_TEXT_4            (ID_PAGE_SUMMARY + 0x05)
#define ID_TEXT_5            (ID_PAGE_SUMMARY + 0x06)
#define ID_TEXT_6            (ID_PAGE_SUMMARY + 0x07)
#define ID_TEXT_7            (ID_PAGE_SUMMARY + 0x08)
#define ID_TEXT_8            (ID_PAGE_SUMMARY + 0x09)
#define ID_TEXT_9            (ID_PAGE_SUMMARY + 0x0A)
#define ID_TEXT_10           (ID_PAGE_SUMMARY + 0x0B)
#define ID_TEXT_11           (ID_PAGE_SUMMARY + 0x0C)
#define ID_TEXT_12           (ID_PAGE_SUMMARY + 0x0D)
#define ID_TEXT_13           (ID_PAGE_SUMMARY + 0x0E)
#define ID_TEXT_14           (ID_PAGE_SUMMARY + 0x0F)
#define ID_TEXT_15           (ID_PAGE_SUMMARY + 0x10)
#define ID_TEXT_16           (ID_PAGE_SUMMARY + 0x11)
#define ID_TEXT_17           (ID_PAGE_SUMMARY + 0x12)
#define ID_TEXT_18           (ID_PAGE_SUMMARY + 0x13)
#define ID_TEXT_19           (ID_PAGE_SUMMARY + 0x14)
#define ID_TEXT_20           (ID_PAGE_SUMMARY + 0x15)
#define ID_TEXT_21           (ID_PAGE_SUMMARY + 0x16)
#define ID_TEXT_22           (ID_PAGE_SUMMARY + 0x17)
#define ID_BUTTON_0 		 (ID_PAGE_SUMMARY + 0x18)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Summary", ID_WINDOW_0, 0, 0, 319, 199, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HEX", ID_TEXT_0, 4, 1, 80, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Chip:", ID_TEXT_1, 20, 20, 80, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Unknow", ID_TEXT_2, 90, 20, 166, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Checksum:", ID_TEXT_3, 20, 40, 68, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Unknow", ID_TEXT_4, 90, 40, 75, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Options:", ID_TEXT_5, 180, 40, 52, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Unknow", ID_TEXT_6, 235, 40, 80, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Limit:", ID_TEXT_7, 20, 58, 34, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Unknow", ID_TEXT_8, 90, 58, 66, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Rolling:", ID_TEXT_9, 20, 163, 48, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Unknow", ID_TEXT_10, 90, 163, 138, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "ENV", ID_TEXT_11, 4, 74, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Vdd(mV):", ID_TEXT_12, 20, 90, 51, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Vpp(mV):", ID_TEXT_13, 180, 90, 51, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Temp:", ID_TEXT_14, 20, 108, 39, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Total", ID_TEXT_15, 4, 130, 35, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "OK:", ID_TEXT_16, 20, 147, 24, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OKVal", ID_TEXT_17, 90, 147, 41, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "NG:", ID_TEXT_18, 180, 147, 21, 14, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NGVal", ID_TEXT_19, 235, 147, 38, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "VddVal", ID_TEXT_20, 90, 90, 42, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "VppVal", ID_TEXT_21, 235, 90, 30, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Not Support", ID_TEXT_22, 90, 108, 81, 14, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 224, 202, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void initSummary(WM_MESSAGE * pMsg)
{
    int32_t            ret;
    uint32_t           num;
    uint32_t           Vol;
    WM_HWIN            hItem;
    struct tlv_chip*   chip;
    struct tlv_code*   code;
    struct tlv_option* option;
    struct tlv_limit*  limit;
    struct tlv_rolling_code* rolling;
    char               buf[128];
    
    //
    // Initialization of 'ChipVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    chip = file_hex_get_chip(0);
    if (chip) {
        TEXT_SetText(hItem, (const char*)chip->name);
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ChecksumVal'
    //
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    code = file_hex_get_code(0);
    if (code) {
        memset(buf, 0, sizeof(buf));
        snprintf(buf, sizeof(buf), "0x%04X", code->checksum);
        TEXT_SetText(hItem, buf); 
    }    
    TEXT_SetFont(hItem, GUI_FONT_13B_1); 
    //
    // Initialization of 'OptionsVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    option = file_hex_get_option(1);
    if (option) {
        int i;
        char tmp[4];
        
        memset(buf, 0, sizeof(buf));
        strcpy(buf, "0x");
        for (i = 0; i < option->option_len; i++) {
            snprintf(tmp, sizeof(tmp), "%02X", option->bytes[i]);
            strcat(buf, tmp);
        }
        TEXT_SetText(hItem, buf); 
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1); 
    //
    // Initialization of 'LimitVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    limit = file_hex_get_limit(0);
    if (limit) {
        if (limit->count == 0) {
            strcpy(buf, "No Limit");
        } else {
            snprintf(buf, sizeof(buf), "%d", limit->count);
        }
        TEXT_SetText(hItem, buf);  
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1); 
    //
    // Initialization of 'RollinVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    rolling = cswrite_cfg_get_rolling_code(0);
    if (rolling) {
        snprintf(buf, sizeof(buf), "%d", rolling->value);
        TEXT_SetText(hItem, buf);
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1);    
    //
    // Initialization of 'OKVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    num = cswrite_log_get_num_ok();
    snprintf(buf, sizeof(buf), "%d", num);
    TEXT_SetText(hItem, buf);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    
    //
    // Initialization of 'NGVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    num = cswrite_log_get_num_failed();
    snprintf(buf, sizeof(buf), "%d", num);
    TEXT_SetText(hItem, buf);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);    
    //
    // Initialization of 'VddVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    ret = power_voltage_get(TLV_DESC_VOLTAGE_TYPE_VDD, &Vol);
    if (!ret) {
        snprintf(buf, sizeof(buf), "%d", Vol);
        TEXT_SetText(hItem, buf);
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'VppVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
    ret = power_voltage_get(TLV_DESC_VOLTAGE_TYPE_VPP, &Vol);
    if (!ret) {
        snprintf(buf, sizeof(buf), "%d", Vol);
        TEXT_SetText(hItem, buf);
    }
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'TempVal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
    TEXT_SetText(hItem, "20.63");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
}

static void keyProcess(WM_MESSAGE* pMsg)
{
    int index;
    WM_HWIN hItem;
    WM_KEY_INFO* keyInfo;

    keyInfo = (WM_KEY_INFO*)pMsg->Data.p;

    printf("[GUI] Summary , %s(),Msg(Key=%d,PressedCnt=%d)\n", __func__, keyInfo->Key, keyInfo->PressedCnt);
    if (keyInfo->Key == KEY_CODE_GUI_HEX_UPGRADED) {
        initSummary(pMsg);
        WM_InvalidateWindow(pMsg->hWin);
    }

    WM_DefaultProc(pMsg);
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'HEX'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'Chip:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Checksum:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Options:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Limit:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Rolling:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'ENV'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'Vdd(mV):'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Vpp(mV):'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Temp:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Total'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    //
    // Initialization of 'OK:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'NG:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00804000));
    // USER START (Optionally insert additional code for further widget initialization)
    initSummary(pMsg);    
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    keyProcess(pMsg);
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSummary
*/
WM_HWIN CreateSummary(void);
WM_HWIN CreateSummary(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
