/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_RADIO_0             (GUI_ID_USER + 0x01)
#define ID_TEXT_0             (GUI_ID_USER + 0x02)
#define ID_TEXT_1             (GUI_ID_USER + 0x03)
#define ID_RADIO_1             (GUI_ID_USER + 0x04)
#define ID_RADIO_2             (GUI_ID_USER + 0x05)
#define ID_TEXT_2             (GUI_ID_USER + 0x06)
#define ID_RADIO_3             (GUI_ID_USER + 0x07)
#define ID_BUTTON_0             (GUI_ID_USER + 0x08)
#define ID_BUTTON_1             (GUI_ID_USER + 0x09)
#define ID_RADIO_4             (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Config", ID_WINDOW_0, 0, 0, 320, 190, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "BuzzerSet", ID_RADIO_0, 18, 23, 74, 40, 0, 0x1402, 0 },
  { TEXT_CreateIndirect, "Buzzer", ID_TEXT_0, 8, 3, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Language", ID_TEXT_1, 109, 4, 80, 20, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "LanguageSet", ID_RADIO_1, 119, 23, 80, 39, 0, 0x1402, 0 },
  { RADIO_CreateIndirect, "ProgOp1", ID_RADIO_2, 19, 83, 106, 60, 0, 0x1403, 0 },
  { TEXT_CreateIndirect, "Program Operation", ID_TEXT_2, 9, 66, 104, 20, 0, 0x64, 0 },
  { RADIO_CreateIndirect, "ProgOp2", ID_RADIO_3, 119, 83, 196, 60, 0, 0x1403, 0 },
  { BUTTON_CreateIndirect, "Quit+NoSave", ID_BUTTON_0, 21, 150, 90, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Quit+Save", ID_BUTTON_1, 207, 151, 90, 20, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "ProgOp3", ID_RADIO_4, 215, 87, 80, 60, 0, 0x1402, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static int configFlag = 0;

static void quitConfig(WM_MESSAGE* pMsg, int saveFlag)
{
    WM_HWIN     hItem;
    int         index;
    WM_HWIN     hMultiPage;
    
    configFlag = 0;    

    hItem = WM_GetParent(pMsg->hWin);
    hMultiPage = WM_GetParent(hItem);

    MULTIPAGE_SelectPage(hMultiPage, 0);
}

static int widgetKeyProcess(WM_MESSAGE* pMsg, WM_HWIN hRadio, int nextId)
{
    int          old;
    int          new;
    WM_HWIN      hItem;
    WM_KEY_INFO* keyInfo;

    keyInfo = (WM_KEY_INFO*)pMsg->Data.p;

    switch (keyInfo->Key) {
    case GUI_KEY_ENTER:
        if (configFlag == 1) {
            old = RADIO_GetValue(hRadio);
            RADIO_Inc(hRadio);
            new = RADIO_GetValue(hRadio);
            if (old == new) {
                if (ID_BUTTON_0 == nextId) {
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_2);
                    WM_SetFocus(hItem);
                } else {
                    RADIO_SetValue(hRadio, 0);
                }
            }
        } else {
            configFlag = 1;
        }
        return 1;
    case GUI_KEY_PGDOWN:
        if (configFlag == 1) {
            hItem = WM_GetDialogItem(pMsg->hWin, nextId);
            WM_SetFocus(hItem);
        } else {
            int index;
            WM_HWIN hMultiPage;

            hItem = WM_GetParent(pMsg->hWin);
            hMultiPage = WM_GetParent(hItem);
            index = MULTIPAGE_GetSelection(hMultiPage);
            hItem = MULTIPAGE_GetWindow(hMultiPage, index);
            if (hItem == pMsg->hWin) {
                MULTIPAGE_SelectPage(hMultiPage, 0);
            } else {
                WM_DefaultProc(pMsg);
            }
        }
        return 1;
    case KEY_CODE_GUI_HEX_UPGRADED:
        printf("[GUI] Hex need update");
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
    return 0;
}



static void keyProcess(WM_MESSAGE* pMsg)
{
    int          ret;
    WM_HWIN      hItem;
    int          Id;

    hItem = WM_GetFocusedWindow();
    Id = WM_GetId(hItem);
    switch (Id) {
    case ID_RADIO_0:
        ret = widgetKeyProcess(pMsg, hItem, ID_RADIO_1);
        return;
    case ID_RADIO_1:
        widgetKeyProcess(pMsg, hItem, ID_RADIO_2);
        return;
    case ID_RADIO_2:
        widgetKeyProcess(pMsg, hItem, ID_BUTTON_0);
        return;
    case ID_RADIO_3:
        widgetKeyProcess(pMsg, hItem, ID_BUTTON_0);
        return;
    case ID_RADIO_4:
        widgetKeyProcess(pMsg, hItem, ID_BUTTON_0);
        return;
    case ID_BUTTON_0:
        widgetKeyProcess(pMsg, 0, ID_BUTTON_1);
        return;
    case ID_BUTTON_1:
        widgetKeyProcess(pMsg, 0, ID_RADIO_0);
        return;
    default:
        break;
    }
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  int     ret;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'BuzzerSet'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "Unmute", 0);
    RADIO_SetText(hItem, "Mute", 1);
    RADIO_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Buzzer'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Language'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'LanguageSet'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
    RADIO_SetText(hItem, "English", 0);
    RADIO_SetText(hItem, "Chinese", 1);
    RADIO_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ProgOp1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_2);
    RADIO_SetText(hItem, "Set by HEX", 0);
    RADIO_SetText(hItem, "Blank Check(B)", 1);
    RADIO_SetText(hItem, "Erase", 2);
    RADIO_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Program Operation'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00408000));
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ProgOp2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_3);
    RADIO_SetText(hItem, "Program(P)", 0);
    RADIO_SetText(hItem, "Verify(V)", 1);
    RADIO_SetFont(hItem, GUI_FONT_13B_1);
    RADIO_SetText(hItem, "Crypto(C)", 2);
    //
    // Initialization of 'Quit+NoSave'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Quit+Save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ProgOp3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_4);
    RADIO_SetText(hItem, "P+V+C", 0);
    RADIO_SetText(hItem, "B+P+V+C", 1);
    RADIO_SetFont(hItem, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_2);
    RADIO_SetGroupId(hItem, 1);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_3);
    RADIO_SetGroupId(hItem, 1);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_4);
    RADIO_SetGroupId(hItem, 1);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_RADIO_0: // Notifications sent by 'BuzzerSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_1: // Notifications sent by 'LanguageSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_2: // Notifications sent by 'ProgOp1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_3: // Notifications sent by 'ProgOp2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Quit+NoSave'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        quitConfig(pMsg, 0);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Quit+Save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        quitConfig(pMsg, 1);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_4: // Notifications sent by 'ProgOp3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    keyProcess(pMsg);
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateConfig
*/
WM_HWIN CreateConfig(void);
WM_HWIN CreateConfig(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
